### ISSUE TITLE
Roadmap to React

### ISSUE THREAD

**Issue by biodavidjm** [biodavidjm/reactDavid#1]
## Reading and tutorials about React

- [ ] [The React.js Way: Getting Started Tutorial](https://blog.risingstack.com/the-react-way-getting-started-tutorial/)
- [ ] [Official React Tutorial](http://facebook.github.io/react/docs/tutorial.html)
- [ ] [Official React Getting Started](http://facebook.github.io/react/docs/getting-started.html)
- [ ] [Understanding the React Component Lifecycle](http://busypeoples.github.io/post/react-component-lifecycle/)
